name: Build and Deploy
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # fetch all commits to get last updated time or other git log info
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm i
    - run: npm run docs:build

    # please check out the docs of the workflow for more details
    # @see https://github.com/crazy-max/ghaction-github-pages
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3
      with:
        # deploy to gh-pages branch
        target_branch: gh-pages
        # deploy the default output dir of VuePress
        build_dir: docs/.vuepress/dist
      env:
        # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}